config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :lists, except: [:edit, :update, :destroy] do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  # les associations [film, liste] doivent être uniques.
  validates_uniqueness_of :movie, :scope => [:list]

  # Le commentaire associé à un signet ne peut pas avoir moins de 6 caractères.
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_one_attached :image

  validates :name, presence: true, uniqueness: true

end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  has_many :lists, through: :bookmarks

  # Un film doit avoir un titre unique et un aperçu.
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @bookmark = Bookmark.new
    @list = List.find(params[:list_id])
    @bookmark.list = @list
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render "lists/show", status: :unprocessable_content
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private
  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_content
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container mt-4">

<h1>Ajouter un film à la liste <em><%= @list.name %></em> :</h1>
 <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :movie_id, collection: Movie.all, label: "Film", prompt: "Sélectionner un film"  %>
    <%= f.input :comment, label: "Note", placeholder: "Ajouter une note" %>
    <%= f.submit 'Ajouter', class:"btn btn-primary"%>
    <%= link_to 'Retour', list_path(@list), class: "btn btn-outline-secondary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to lists_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Mes listes", lists_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Nouvelle liste", new_list_path, class: "nav-link" %>

          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>

    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner"
  style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://images.unsplash.com/photo-1513106580091-1d82408b8cd6?q=80&w=2352&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D, height: 300, crop: :fill %>')"
>
  <div class="container">
    <h1>Mes listes de film</h1>
  </div>
</div>


<div class="container">
  <div class="cards-custom">
    <% @lists.each do |list| %>
    <% if list.image.attached? %>
    <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.image.key, height: 300, crop: :fill %>')">
    <% end %>
      <p><%= link_to list.name, list_path(list), class: "card-title" %></p>
    </div>
    <% end %>
  </div>

  <%= link_to "Créer une nouvelle liste", new_list_path, class: "btn btn-primary" %>
</div>

app/views/lists/new.html.erb
<div class="container mt-4">
  <h1>Créer une liste</h1>

  <%= simple_form_for @list do |f| %>
    <%= f.input :name, label: "Nom de la liste" %>
    <%= f.input :image, as: :file, label: "Image" %>
    <%= f.submit 'Créer', class: "btn btn-primary" %>
    <%= link_to 'Retour', lists_path, class: "btn btn-outline-secondary" %>
    <% end %>

</div>

app/views/lists/show.html.erb
<%# BANNER %>

<% if @list.image.attached? %>
  <div class="banner"
    style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @list.image.key, height: 300, crop: :fill %>')">
<% end %>

  <div class="container">
    <h1><%= @list.name %></h1>
  </div>
</div>

<%# CARDS %>

<div class="container mt-4 mb-5">
  <div class="row row-cols-3">
    <% @list.movies.each do |movie| %>
    <div class="col d-flex flex-wrap">
      <div class="card">
        <%= image_tag movie.poster_url, class: "card-img-top ", alt: "poster" %>
        <div class="card-body">
          <h5 class="card-text fw-bold"><%= movie.title %></h5>
          <p class="card-text"><%= movie.overview %></p>
          <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
          <div class="d-flex justify-content-between align-items-center">
            <figcaption class="blockquote-footer mt-2">
            <%= bookmark.comment %>
            </figcaption>
            <%= link_to bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Supprimer ?" } do %>
            <i class="fa-solid fa-trash mb-1"></i>
            <% end %>
          </div>
        </div>
      </div>
      </div>
    <% end %>
    </div>

<%# CTA %>

  <%= link_to "Ajouter un film", new_list_bookmark_path(@list), class: "btn btn-primary mt-4" %>
  <%= link_to "Voir toutes les listes", lists_path, class: "btn btn-outline-secondary mt-4" %>
</div>